on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: JaganPaineedi/hello-world-composite-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: pwsh
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
